version: "3.3"

services:
  logistics_db:
    container_name: logistics_db
    hostname: logistics_db
    image: postgres:13.3
    restart: always
    user: root
    networks:
      - default
      - kafka-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=logistics
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - "5433:5432"

  logistics_db_shard_1:
    container_name: logistics_db_shard_1
    hostname: logistics_db_shard_1
    image: postgres:13.3
    restart: always
    networks:
      - default
      - kafka-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=logistics
    volumes:
      - ./postgres-data-1:/var/lib/postgresql
    ports:
      - "5451:5432"

  logistics_db_shard_2:
    container_name: logistics_db_shard_2
    hostname: logistics_db_shard_2
    image: postgres:13.3
    restart: always
    networks:
      - default
      - kafka-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=logistics
    volumes:
      - ./postgres-data-2:/var/lib/postgresql
    ports:
      - "5452:5432"

  logistics_db_migrations:
    container_name: logistics_db_migrations
    build: ./
    command: /bin/sh -c "/usr/local/bin/goose postgres up -dir ./migrations"
    networks:
      - default
      - kafka-net
    depends_on:
      - logistics_db

  logistics_db_migrations_1:
    build:
      context: .
      dockerfile: Dockerfile-shards
      args:
        MIG_DIR: shard_migrations_0
    container_name: logistics_db_migrations_1
    command: /bin/sh -c "sleep 3 && goose postgres \"host=logistics_db_shard_1 port=5432 user=postgres password=postgres dbname=logistics sslmode=disable\" up"
    networks:
      - default
      - kafka-net
    depends_on:
      - logistics_db_shard_1

  logistics_db_migrations_2:
    build:
      context: .
      dockerfile: Dockerfile-shards
      args:
        MIG_DIR: shard_migrations_1
    container_name: logistics_db_migrations_2
    command: /bin/sh -c "sleep 3 && goose postgres \"host=logistics_db_shard_2 port=5432 user=postgres password=postgres dbname=logistics sslmode=disable\" up"
    networks:
      - default
      - kafka-net
    depends_on:
      - logistics_db_shard_2

  logistics_service:
    container_name: logistics_service
    build: ./
    command: /bin/sh -c "/usr/local/bin/logistics"
      - default
      - kafka-net
    ports:
      - "8401:8401"
      - "8501:8501"
    depends_on:
      - redis
      - logistics_db
      - logistics_db_migrations

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - '6380:6379'
    environment:
      - REDIS_PASSWORD=redis_pass
    networks:
      - default
      - kafka-net

networks:
  default:
  kafka-net:
    driver: bridge