version: "3.3"

services:
  logistics_db:
    container_name: logistics_db
    image: postgres:13.3
    restart: always
    user: root
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=logistics
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - "5433:5432"

  logistics_db_migrations:
    container_name: logistics_db_migrations
    build: ./
    command: /bin/sh -c "/usr/local/bin/goose postgres up -dir ./migrations"
    depends_on:
      - logistics_db

  logistics_service:
    container_name: logistics_service
    build: ./
    command: /bin/sh -c "/usr/local/bin/logistics"
    depends_on:
      - logistics_db
      - logistics_db_migrations
