
application:
  name: "logistics"
  testData: true

cache:
  redis:
    host: 172.17.0.1
    port: 6380
    password: redis_pass

tracing:
  jaeger:
    host: 172.17.0.1
    port: 6831

database:
  dbms: "postgres"
  db: "logistics"
#  host: logistics_db
  host: 172.17.0.1
  port: 5433
  user: "postgres"
  password: "postgres"

kafka:
  brokers:
    - host: "172.17.0.1"
      port: 19092
    - host: "172.17.0.1"
      port: 29092
    - host: "172.17.0.1"
      port: 39092

  issueOrderTopics:
    issueOrder: "IssueOrder"
    removeOrder: "RemoveOrder"
    markOrderIssued: "MarkOrderIssued"
    undoIssueOrder: "UndoIssueOrder"
    confirmIssueOrder: "ConfirmIssueOrder"
